name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 14
      uses: actions/setup-java@main
      with:
        java-version: 14

    - name: Build project with Maven
      run: |
        cd HelloWorld
        mvn -B package --file pom.xml
