name: Java CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 21
      uses: actions/setup-java@main
      with:
        distribution: temurin
        java-version: 21
    - run: $(find . -type f -name '*.java') | sudo java
